name: Nx affected
description: Run a Nx task for the affected applications/libraries

inputs:
    baseRef:
        description: Ref to compare the current state to
        required: true

    target:
        description: Nx target to run
        required: true

    parallel:
        description: How many parallel tests to run
        required: false

runs:
    using: "composite"
    steps:
        - if: ${{ inputs.parallel != '' }}
          run: yarn nx affected --base ${{ inputs.baseRef }} --target ${{ inputs.target }} --parallel=${{ inputs.parallel }}
          shell: bash
        - if: ${{ inputs.parallel == '' }}
          run: yarn nx affected --base ${{ inputs.baseRef }} --target ${{ inputs.target }}
          shell: bash
