on:
    workflow_call:
        inputs:
            baseRef:
                required: true
                type: string

jobs:
    test:
        name: e2e
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "yarn"

            - run: yarn install --frozen-lockfile

            - uses: ./.github/actions/nx-affected
              name: "Nx affected: e2e"
              with:
                  baseRef: ${{ inputs.baseRef }}
                  target: e2e
                  parallel: 1
