name: Pull Request
on: [pull_request]
jobs:
    test:
        name: Unit Test
        uses: ./.github/workflows/_test-unit.yml
        with:
            baseRef: origin/main
    e2e:
        name: e2e Test
        uses: ./.github/workflows/_test-e2e.yml
        with:
            baseRef: origin/main
